language: haskell

sudo: false

addons:
  apt:
    packages:
    - opam
#    - haskell-platform
#    - cabal-install

env:
 matrix:
  - AGDA="yes"  INTERNAL_COQ=""     AXIOMATIZATION=""
#  - AGDA=""     INTERNAL_COQ="yes"  AXIOMATIZATION=""
  - AGDA=""     INTERNAL_COQ=""     AXIOMATIZATION="yes"

before_script:
 - uname -a
 - export PATH="$HOME/cache/.cabal-sandbox/bin:$PATH"
 - mkdir -p "$HOME/cache"
 - if [ ! -z "$AGDA" ]; then cabal update || true; fi
 - if [ ! -z "$AGDA" ]; then (cd "$HOME/cache" && cabal sandbox init); fi
 - if [ ! -z "$AGDA" ]; then (cd "$HOME/cache" && cabal install Agda); fi
 - if [ ! -z "$AXIOMATIZATION$INTERNAL_COQ" ]; then (cd "$HOME/cache" && opam update); fi
 - if [ ! -z "$AXIOMATIZATION$INTERNAL_COQ" ]; then (cd "$HOME/cache" && opam list && opam install -j4 -v coq.8.5~beta2); fi

script: false
