language: haskell

ghc:
  - 7.8.4

sudo: false

cache:
 directories:
  - $HOME/cache
  - $HOME/.opam
  - $HOME/.cabal

addons:
  apt:
    sources:
     - avsm
    packages:
     - opam

env:
 matrix:
  - AGDA="yes"      COQ=""    AGDA_VERSION="2.4.2.5" REBUILD_CACHE="" TARGETS="agda"
  - AGDA=""         COQ=""    AGDA_VERSION="2.4.2.5" REBUILD_CACHE="" TARGETS="coq"
  - AGDA=""         COQ="yes" AGDA_VERSION="2.4.2.5" REBUILD_CACHE="" TARGETS="coq-axiomatization"

install:
 - export PATH="$HOME/cache/.cabal-sandbox/bin:$HOME/.cabal/bin:$PATH"
# - rm -rf $HOME/cache
 - mkdir -p "$HOME/cache"
 - cat $HOME/.cabal/config
 - if [ ! -z "$AGDA$REBUILD_CACHE" -a ! -d "$HOME/cache/.cabal-sandbox" ]; then (cd "$HOME/cache" && cabal sandbox init); fi
 - if [ ! -z "$AGDA$REBUILD_CACHE" ]; then cabal update; fi
 - if [ ! -z "$AGDA$REBUILD_CACHE" ]; then cabal install alex; fi
 - if [ ! -z "$AGDA$REBUILD_CACHE" ]; then cabal install happy; fi # https://github.com/SublimeHaskell/SublimeHaskell/issues/184
 - if [ ! -z "$AGDA$REBUILD_CACHE" ]; then (cd "$HOME/cache" && cabal install 'cpphs <1.20' Agda-$AGDA_VERSION); fi


before_script:
 - uname -a
 - if [ ! -z "$COQ$REBUILD_CACHE" ]; then opam init -y --auto-setup; fi
 - if [ ! -z "$COQ$REBUILD_CACHE" ]; then opam update; fi
 - if [ ! -z "$COQ$REBUILD_CACHE" ]; then opam repo add coq-core-dev https://coq.inria.fr/opam/core-dev || true; fi
 - if [ ! -z "$COQ$REBUILD_CACHE" ]; then opam repo add coq-released https://coq.inria.fr/opam/released || true; fi
 - if [ ! -z "$COQ$REBUILD_CACHE" ]; then eval `opam config env`; fi
 - if [ ! -z "$COQ$REBUILD_CACHE" ]; then opam list -a; fi
 - if [ ! -z "$COQ$REBUILD_CACHE" ]; then coqc -v || true; fi
 - if [ ! -z "$COQ$REBUILD_CACHE" ]; then echo | coqtop || true; fi
 - if [ ! -z "$COQ$REBUILD_CACHE" ]; then opam install -y -j4 -v coq.8.5~beta2; fi
 - if [ ! -z "$COQ$REBUILD_CACHE" ]; then opam list -a; fi
 - if [ ! -z "$COQ$REBUILD_CACHE" ]; then opam install -y -j4 -v coq-template-coq.1.0.0~beta2; fi
 - if [ ! -z "$COQ$REBUILD_CACHE" ]; then opam list -a; fi
 - if [ ! -z "$COQ$REBUILD_CACHE" ]; then eval `opam config env`; fi

script: make $TARGETS
